### ISSUE TITLE
B&W logo looks bad in QGIS

### ISSUE THREAD

**Issue by timlinux** [klakar/qgis_logo#1]
Hi @klakar 

I am making a little patch to install some of your SVG logos by default in QGIS so we can easily add it to our maps.

![qgis-logo-patch](https://user-images.githubusercontent.com/178003/101517004-18ced900-3978-11eb-84fa-2c625bb9b80e.gif)

For the colour logo it works fine, the black one does this when adding it in composer:

![image](https://user-images.githubusercontent.com/178003/101516990-140a2500-3978-11eb-895e-61b2fbe62a64.png)

Do you not get this on your side?

**Comment by klakar** [comment]
I did, but not anymore. I've been using another source for the logo lately, maybe that one is the fixed one...
https://github.com/klakar/QGIS_resources/blob/master/collections/Geosupportsystem/svg/madeWithQGIS.svg
I'll check my self in a day or two.. .
